### ISSUE TITLE
Comment ajouter le mod ?

### ISSUE THREAD

**Issue by Zedtsuki** [TheOptimisticFactory/LoupGarou#1]
Bonjour et merci pour l'ajout de ce mod super interessant !

Ma question est simple, comment ajouter le mod ?

J'ai supposé qu'il fallait juste copier le contenu du dossier et le coller dans celui de base en remplaçant les fichiers, pourtant les commandes ne sont pas reconnues lorsque je me connecte sur le serveur ?

Faut il procéder différemment ? ^^

Merci !

**Comment by Zedtsuki** [comment]
C'est bon j'ai fini par trouver :)

**Comment by TheOptimisticFactory** [comment]
Plus de 4 ans plus tard, je découvre qu'il existe des issue sur ce fork.

Je viens de clarifier dans le README la façon recommandée de lancer ce projet: https://github.com/TheOptimisticFactory/LoupGarou?tab=readme-ov-file#how-to-run-the-project

Pour ceux qui liraient ceci à l'avenir, je recommande d'utiliser l'installation serveur préconfigurée dans mon autre repository: https://github.com/TheOptimisticFactory/java-minecraft-loupGarou-server
