### ISSUE TITLE
Update 1.16.3

### ISSUE THREAD

**Issue by BlackRec** [TheOptimisticFactory/LoupGarou#4]
Penses-tu pouvoir mettre ton plugin en 1.16.3 ? Super version mise à jour du loup garou en tout cas ! Merci pour ton travail !

**Comment by TheOptimisticFactory** [comment]
Bonjour,

Je débarque avec plus de 4 ans de retard pour cette question. Mon fork n'avait vocation qu'à rajouter des fonctionnalités au projet existant, lequel a officiellement été archivé il y a ça quelques jours.

Je n'ai pas pour projet de mettre à jour ce plugin, mais accepterai volontiers de l'ajouter via pull-request si quelqu'un souhaite implémenter le support des version plus récentes de Minecraft.
